In [1]:
import numpy as np
from decomposition.game import Game

Create structure of game. We allow that the computed structure is saved or loaded (if already existent), i.e., *save_load=True*. If no path is given, we use the current working directory and create a directory *data/structure/*.

In [2]:
game = Game([2,2], save_load=True, path="../")

We consider the Chicken Game and create the respective payoff matrices. We then compute the decomposition and observe that this version is actually a potential game:

In [3]:
payoff_matrices = [
    np.array([[0, 10], [-1, -100]]), np.array([[0, -1], [10, -100]])
]
game.compute_decomposition_matrix(payoff_matrices)
print(f"Potentialness {game.metric:.05f}")

Potentialness 1.00000


If we consider Matching Pennies instead, we observe that it is a harmonic game: 

In [4]:
payoff_matrices = [
    np.array([[1, -1], [-1, 1]]), np.array([[-1, 1], [1, -1]])
]
game.compute_decomposition_matrix(payoff_matrices)
print(f"Potentialness {game.metric:.05f}")

Potentialness 0.00000


Let us consider some other random game:

In [10]:
payoff_matrices = [
    np.array([[1, -2], [3, -4]]), np.array([[4, -3], [2, -1]])
]
game.compute_decomposition_matrix(payoff_matrices)
print(f"Potentialness {game.metric:.05f}")

Potentialness 0.63870


The potential and harmonic components are given by

In [14]:
np.round(game.uP,3)

array([[[-0. , -0. ],
        [ 0. ,  0. ]],

       [[ 2.5, -2.5],
        [ 2.5, -2.5]]])

In [15]:
np.round(game.uH,3)

array([[[-1.,  1.],
        [ 1., -1.]],

       [[ 1., -1.],
        [-1.,  1.]]])

The original game can be reconstructed by adding up the potential, harmonic, and non-strategic components:

In [19]:
np.array(game.uP) + np.array(game.uH) + np.array(game.uN)

array([[[ 1., -2.],
        [ 3., -4.]],

       [[ 4., -3.],
        [ 2., -1.]]])

For a faster computation, one can also compute the potentialness in the flow space. Note that this doesn't give you the decomposition (uP, uH, and uN)

In [25]:
game = Game([2,2], flow_space=True, save_load=True, path="../")
game.compute_flow_decomposition_matrix(payoff_matrices)
print(f"Potentialness {game.flow_metric:.05f}")

Potentialness 0.63870
